version: "3.8"

networks:
  capstone-backend:

services:
  postgres:
    container_name: postgres-capstone
    image: postgres
    environment:
      POSTGRES_PASSWORD: postgres
    ports:
      - "5432:5432"
    volumes:
      - pgdata:/var/lib/postgresql/data
    networks:
      - capstone-backend

  redis:
    image: redis:6.0.7
    container_name: redis-capstone
    volumes:
      - redis_volume_data:/data
    ports:
      - 6379:6379
    networks:
      - capstone-backend

  capstone:
    image: dihson103/capstone:v5.6
    container_name: capstone
    environment:
      - ASPNETCORE_ENVIRONMENT=Development
      - ConnectionStrings__DefaultConnection=Server=postgres-capstone:5432;User Id=postgres;Password=postgres;Database=CapstoneProject
      - ConnectionStrings__Redis=redis:6379
      - Jwt__Issuer=http://capstone:7001
      - Jwt__Audience=http://capstone:7001
      - Jwt__SecretKey=BSMiu0y9GwkHjCTy8J3gqfivqzdzNQp6
      - GoogleCredentialFile=capstone-426620-071d9a42b286.json
      - GoogleCloudStorageBucket=capston-storage
    ports:
      - 7001:8080
    depends_on:
      - postgres
      - redis
    networks:
      - capstone-backend

  nginx:
    image: nginx:latest
    container_name: reverse_proxy
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
    ports:
      - 80:80
    depends_on:
      - capstone
    networks:
      - capstone-backend

volumes:
  pgdata:
  redis_volume_data:
  redis_insight_volume_data:
